# -*- coding: utf-8 -*-
"""weAther.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iPPr11_Gzq74s3ojEPdjGdT4RZdFWMop
"""

import pandas as pd
data=pd.read_csv(r"weather.csv")
#print(data["Wind Speed_km/h"].unique)
#data_clear_count=data[data["Weather"]=="Clear"]
#print(data_clear_count)

data_clear_count=data[data["Weather"]=="Clear"]
print(data_clear_count)

data_speed_4km=data[data["Wind Speed_km/h"]==4]
print(data_speed_4km)

print(data.isnull())

data.rename(columns={"Weather":"Weather Condition"})

data_mean_visibility=data["Visibility_km"].mean()
print(data_mean_visibility)

std_pressure=data["Press_kPa"].std()
print(std_pressure)

varience_hum=data["Rel Hum_%"].var()
print(varience_hum)

data_snow_count=data[data["Weather"]=="Snow"]
print(data_snow_count)

wind_vis=data[(data["Wind Speed_km/h"]<24) & (data["Visibility_km"]==25)]
print(wind_vis)

mean_each=data.groupby("Weather").mean()
print(mean_each)

max_min_each=data.groupby("Weather").agg(['min','max'])
print(max_min_each)

data_fog_count=data[data["Weather"]=="Fog"]
print(data_fog_count)

wind_vis2=data[(data["Weather"]=="clear")|(data["Visibility_km"]>40)]
print(wind_vis2)

wind_vis3=data[(data["Weather"]=="clear")|(data["Rel Hum_%"]>50)]
print(wind_vis3)

wind_vis2=data[(data["Visibility_km"]>40)]
print(wind_vis2)